EventManagementSystem/Models/EventsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventManagementSystem.Models
{
    public class EventEntityViewModel
    {
        public EventEntity EventEntity { get; set; }

        public IEnumerable<UserEntity> Users { get; set; }

        public EventEntityViewModel()
        {

        }

        public EventEntityViewModel(IUnitOfModel model)
        {
            EventEntity = new EventEntity();
            Users = from u in model.UsersRepo.GetAll()
                    join r in model.UserRolesRepo.GetAll() on u.UserRoleId equals r.UserRoleId
                    where r.RoleName.Equals("Host")
                    select u;
        }
    }

    public class EventDataUI
    {
        public EventDataUI()
        {

        }
        public int EventId { get; set; }
        public int UserId { get; set; }

        public bool IsSubscribed { get; set; }

        public string EventName { get; set; }

        public string HostName { get; set; }

        public string UserName { get; set; }

        public bool IsApproved { get; set; }
    }

    public class EventsViewModel
    {
        public IEnumerable<EventDataUI> EventData { get; set; }

        public EventsViewModel()
        {

        }

        public EventsViewModel(IUnitOfModel model, int userId = 0)
        {
            if (userId > 0)
                EventData = model.EventsRepo.ViewSubscribedEvents(userId);
            else
                EventData = model.EventsRepo.ViewEvents();
        }
    }

    public class EventsApproveViewModel
    {
        public IEnumerable<EventDataUI> EventData { get; set; }

        public EventsApproveViewModel(IUnitOfModel model)
        {
            EventData = model.EventsRepo.ViewApprovalEvents();
        }
    }
}

EventManagementSystem/Controllers/EventController.cs
using EventManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventManagementSystem.Controllers
{
    public class EventController : Controller
    {
        readonly IUnitOfModel model;

        public EventController()
        {
            model = SingletonOfModel.Instance;
        }

        public EventController(IUnitOfModel unitOfModel)
        {
            model = unitOfModel;
        }

        public ActionResult ApproveEvents()
        {
            var eventsVM = new EventsApproveViewModel(model);
            return View("Admin", "_Layout", eventsVM.EventData);
        }

        // GET: Event
        public ActionResult Index()
        {
            var roleName = Convert.ToString(Session["UserRole"]);
            if (roleName.Equals("Admin"))
            {
                var eventsVM = new EventsViewModel(model, 0);
                return View("Host", "_Layout", eventsVM.EventData);
            }
            else if (roleName.Equals("Host"))
            {
                var eventsVM = new EventsViewModel(model, Convert.ToInt16(Session["UserId"]));
                return View("Host", "_Layout", eventsVM.EventData);
            }
            else
            {
                var eventsVM = new EventsViewModel(model, Convert.ToInt16(Session["UserId"]));
                return View("Index", "_Layout", eventsVM.EventData);
            }
        }

        //[HttpPost]
        //public ActionResult MultipleCommand(EventDataUI eventUI, string command)
        //{
        //    if (command.ToLower().Equals("new"))
        //        return Create;
        //    if (command.ToLower().Equals("sub"))
        //        return Subscribe();

        //    return Index();
        //}
        public ActionResult Subscribe(int eventId)
        {
            if (eventId > 0)
            {
                var userId = Convert.ToInt16(Session["UserId"]);
                model.EventSubsRepo.Add(new EventSubscriptionEntity()
                { EventId = eventId, UserId = userId });
                model.Commit();

                ViewBag.result = Constants.EventSubscribed;
            }

            return Index();
        }

        public ActionResult Approve(int eventId, int userId)
        {
            var evs = model.EventSubsRepo.GetAll().FirstOrDefault(s => s.EventId == eventId
                        && s.UserId == userId);
            evs.IsApproved = true;
            model.Commit();
            ViewBag.result = Constants.EventApproved;

            return Index();
        }

        public ActionResult ViewAttendees(int eventId)
        {
            if (eventId > 0)
            {
                var vmModel = from m in model.EventsRepo.ViewAttendees(eventId)
                              select new UserViewModel { UserName = m };

                return View("ViewAttendees", "_Layout", vmModel);
            }

            return View();
        }

        public ActionResult Create()
        {
            var eventsVM = new EventEntityViewModel(model);
            return View("Create", "_Layout", eventsVM);
        }

        [HttpPost]
        public ActionResult CreateEvent(EventEntityViewModel eventVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.EventsRepo.Add(eventVM.EventEntity);
                    model.Commit();
                    ViewBag.result = Constants.EventCreated;
                }
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }

            return RedirectToAction("Create");
        }
    }
}

EventManagementSystem/Views/Event/Admin.cshtml
@model IEnumerable<EventManagementSystem.Models.EventDataUI>

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/_ViewStart.cshtml";
    WebGrid webGrid = new WebGrid(source: Model);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        .Grid {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }

            .Grid th {
                background-color: #F7F7F7;
                font-weight: bold;
            }

            .Grid th, .Grid td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            .Grid, .Grid table td {
                border: 0px solid #ccc;
            }

                .Grid th a, .Grid th a:visited {
                    color: #333;
                }
    </style>
</head>
<body>

    @using (Html.BeginForm("MultipleCommand", "Event", FormMethod.Post, new { id = "submitForm" }))
    {
        @Html.AntiForgeryToken()
        <table>
            <tr>
                <td>
                    @webGrid.GetHtml(
                            htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
                            columns: webGrid.Columns(
                        webGrid.Column("EventName", "Event Name"),
                        webGrid.Column("HostName", "User Name"),
                        webGrid.Column(header: "Action", format: (item) => !item.IsApproved ?
                    Html.ActionLink("Approve", "Approve", new { eventId = item.EventId, userId = item.UserId }) : new HtmlString("Approved"))))

                </td>
            </tr>
            <tr>
                <td height="5">

                </td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Create", "Create", "Event")
                </td>
            </tr>
        </table>
    }
</body>
</html>

EventManagementSystem/Views/Event/Create.cshtml
@model EventManagementSystem.Models.EventEntityViewModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }

            table th {
                background-color: #F7F7F7;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <h3>@ViewBag.result</h3>
    @using (Html.BeginForm("CreateEvent", "Event", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
    <table border="0" cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="3">
                Add Event
            </th>
        </tr>
        <tr>
            <td>
                Event Name
            </td>
            <td>
                @Html.TextBoxFor(model => model.EventEntity.EventName, new { htmlAttributes = new { @class = "form-control" } })
                <br />
                @Html.ValidationMessageFor(model => model.EventEntity.EventName, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                Host Name
            </td>
            <td>
                @Html.DropDownListFor(model => model.EventEntity.HostId, new SelectList(Model.Users, "UserId", "UserName"),
               htmlAttributes: new { @class = "form-control", id = "User" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add" />
            </td>
        </tr>
    </table>
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @if (@ViewBag.Message != null)
    {
        <script type="text/javascript">
            $(function () {
                alert("@ViewBag.Message")
            });
        </script>
    }
</body>
</html>

EventManagementSystem/Views/Event/Host.cshtml
@model IEnumerable<EventManagementSystem.Models.EventDataUI>

@{
    ViewBag.Title = "Host";
    Layout = "~/Views/_ViewStart.cshtml";
    WebGrid webGrid = new WebGrid(source: Model);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        .Grid {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }

            .Grid th {
                background-color: #F7F7F7;
                font-weight: bold;
            }

            .Grid th, .Grid td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            .Grid, .Grid table td {
                border: 0px solid #ccc;
            }

                .Grid th a, .Grid th a:visited {
                    color: #333;
                }
    </style>
</head>
<body>

    @using (Html.BeginForm("MultipleCommand", "Event", FormMethod.Post, new { id = "submitForm" }))
    {
        @Html.AntiForgeryToken()
        <table>
            <tr>
                <td>
                    @webGrid.GetHtml(
                            htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
                            columns: webGrid.Columns(
                        webGrid.Column("EventName", "Event Name"),
                        webGrid.Column("HostName", "Host Name"),
                        webGrid.Column(header: "Action", format: (item) =>
                        Html.ActionLink("View Attendees", "ViewAttendees", new { eventId = item.EventId }))))

                </td>
            </tr>
        </table>
    }
</body>
</html>

EventManagementSystem/Views/Event/Index.cshtml
@model IEnumerable<EventManagementSystem.Models.EventDataUI>

@{
    Layout = "~/Views/_ViewStart.cshtml";
    WebGrid webGrid = new WebGrid(source: Model);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        .Grid {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }

            .Grid th {
                background-color: #F7F7F7;
                font-weight: bold;
            }

            .Grid th, .Grid td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            .Grid, .Grid table td {
                border: 0px solid #ccc;
            }

                .Grid th a, .Grid th a:visited {
                    color: #333;
                }
    </style>
</head>
<body>

    @using (Html.BeginForm("MultipleCommand", "Event", FormMethod.Post, new { id = "submitForm" }))
    {
        @Html.AntiForgeryToken()
        <table>
            <tr>
                <td>
                    @webGrid.GetHtml(
                            htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
                            columns: webGrid.Columns(
                        webGrid.Column("EventName", "Event Name"),
                        webGrid.Column("HostName", "Host Name"),
                    webGrid.Column(header: "Action", format: (item) => !item.IsSubscribed ? 
                    Html.ActionLink("Subscribe", "Subscribe", new { eventId = item.EventId }) : new HtmlString("Subscribed"))))

                </td>
            </tr>
        </table>
    }
</body>
</html>

EventManagementSystem/Views/Event/ViewAttendees.cshtml
@model IEnumerable<EventManagementSystem.Models.UserViewModel>

@{
    Layout = "~/Views/_ViewStart.cshtml";
    WebGrid webGrid = new WebGrid(source: Model);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        .Grid {
            border: 1px solid #ccc;
            border-collapse: collapse;
        }

            .Grid th {
                background-color: #F7F7F7;
                font-weight: bold;
            }

            .Grid th, .Grid td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            .Grid, .Grid table td {
                border: 0px solid #ccc;
            }

                .Grid th a, .Grid th a:visited {
                    color: #333;
                }
    </style>
</head>
<body>

    @using (Html.BeginForm("MultipleCommand", "Event", FormMethod.Post, new { id = "submitForm" }))
    {
        @Html.AntiForgeryToken()
        <table>
            <tr>
                <td>
                    @webGrid.GetHtml(
             htmlAttributes: new { @id = "WebGrid", @class = "Grid" },
             columns: webGrid.Columns(
         webGrid.Column("UserName", "User Name")))
                </td>
            </tr>
        </table>
    }
</body>
</html>